package com.maximoapps.in.localgudie_mapnavigation.database;


import android.annotation.SuppressLint;

import java.text.SimpleDateFormat;
import java.util.Calendar;

public class DatabaseDetail {

	public static String TABLE_USER_REGISTRATION="REGISTER_USER";
	public static String[] COLUMNS_USER_REGISTRATION;
	public static String[] getColumns_USER_REGISTRATION(){
		COLUMNS_USER_REGISTRATION=new String[23];
		COLUMNS_USER_REGISTRATION[0]="USER_OID";
		COLUMNS_USER_REGISTRATION[1]="USER_PHONE";
		COLUMNS_USER_REGISTRATION[2]="USER_NAME";
		COLUMNS_USER_REGISTRATION[3]="USER_EMAIL";
		COLUMNS_USER_REGISTRATION[4]="USER_DOB";
		COLUMNS_USER_REGISTRATION[5]="USER_GENDER";
		COLUMNS_USER_REGISTRATION[6]="IMAGE_PATH";
		COLUMNS_USER_REGISTRATION[7]="USER_PASSWORD";
		COLUMNS_USER_REGISTRATION[8]="IMAGE_VISIBILITY";
		COLUMNS_USER_REGISTRATION[9]="DOB_VISIBILITY";
		COLUMNS_USER_REGISTRATION[10]="GENDER_VISIBILITY";
		COLUMNS_USER_REGISTRATION[11]="LOGIN_STATUS";
		COLUMNS_USER_REGISTRATION[12]="USER_COUNTRY";
		COLUMNS_USER_REGISTRATION[13]="PROFESSION";
		COLUMNS_USER_REGISTRATION[14]="PROFESSION_DESCRIPTION";
		COLUMNS_USER_REGISTRATION[15]="USER_RATING_1";
		COLUMNS_USER_REGISTRATION[16]="USER_RATING_2";
		COLUMNS_USER_REGISTRATION[17]="USER_RATING_3";
		COLUMNS_USER_REGISTRATION[18]="USER_RATING_4";
		COLUMNS_USER_REGISTRATION[19]="USER_RATING_5";
		COLUMNS_USER_REGISTRATION[20]="STATUS";
		COLUMNS_USER_REGISTRATION[21]="CREATION_DATE";
		COLUMNS_USER_REGISTRATION[22]="MODIFIED_DATE";


		return COLUMNS_USER_REGISTRATION;

	}

	public static String TABLE_MILAAP_CONTACTS="MILAAP_CONTACTS";
	public static String[] COLUMNS_MILAAP_CONTACTS;
	public static String[] getColumns_MILAAP_CONTACTS(){
		COLUMNS_MILAAP_CONTACTS=new String[9];
		COLUMNS_MILAAP_CONTACTS[0]="CONTACTS_ID";
		COLUMNS_MILAAP_CONTACTS[1]="PHONE_NUM";
		COLUMNS_MILAAP_CONTACTS[2]="CONTACTS_NAME";
		COLUMNS_MILAAP_CONTACTS[3]="USER_OID";
		COLUMNS_MILAAP_CONTACTS[4]="CONTACT_TYPE";
		COLUMNS_MILAAP_CONTACTS[5]="CONNECTION_STATUS";
		COLUMNS_MILAAP_CONTACTS[6]="SERVER_NUMBER";
		COLUMNS_MILAAP_CONTACTS[7]="STATUS";
		COLUMNS_MILAAP_CONTACTS[8]="CREATION_DATE";

		return COLUMNS_MILAAP_CONTACTS;

	}


	public static String TABLE_REGISTER_DEVICE="REGISTER_DEVICE";
	public static String[] COLUMNS_REGISTER_DEVICE;
	public static String[] getColumns_REGISTER_DEVICE(){
		COLUMNS_REGISTER_DEVICE=new String[5];
		COLUMNS_REGISTER_DEVICE[0]="GCM_CODE";
		COLUMNS_REGISTER_DEVICE[1]="OS_VERSION";
		COLUMNS_REGISTER_DEVICE[2]="DEVICE_OID";
		COLUMNS_REGISTER_DEVICE[3]="STATUS";
		COLUMNS_REGISTER_DEVICE[4]="LAST_DATE";

		return COLUMNS_REGISTER_DEVICE;

	}




	public static String TABLE_CHAT_HISTORY="CHAT_HISTORY";
	public static String[] COLUMNS_CHAT_HISTORY;
	public static String[] getColumns_CHAT_HISTORY(){
		COLUMNS_CHAT_HISTORY=new String[8];
		COLUMNS_CHAT_HISTORY[0]="GRP_INDI";
		COLUMNS_CHAT_HISTORY[1]="FROM_OID";
		COLUMNS_CHAT_HISTORY[2]="TO_OID";
		COLUMNS_CHAT_HISTORY[3]="MEET_OID";
		COLUMNS_CHAT_HISTORY[4]="CHAT_MESSAGE";
		COLUMNS_CHAT_HISTORY[5]="GROUP_CODE";
		COLUMNS_CHAT_HISTORY[6]="STATUS";
		COLUMNS_CHAT_HISTORY[7]="CREATION_DATE";


		return COLUMNS_CHAT_HISTORY;

	}


	public static String TABLE_MEETUPS="MEETUPS";
	public static String[] COLUMNS_MEETUPS;
	public static String[] getColumns_MEETUPS(){
		COLUMNS_MEETUPS=new String[15];
		COLUMNS_MEETUPS[0]="TYPE";
		COLUMNS_MEETUPS[1]="MEET_OID";
		COLUMNS_MEETUPS[2]="FROM_OID";
		COLUMNS_MEETUPS[3]="TO_OID";
		COLUMNS_MEETUPS[4]="LAT";
		COLUMNS_MEETUPS[5]="LONGI";
		COLUMNS_MEETUPS[6]="PLACE_NAME";
		COLUMNS_MEETUPS[7]="GROUP_CODE";
		COLUMNS_MEETUPS[8]="GRP_INDI";
		COLUMNS_MEETUPS[9]="FROM_TAG";
		COLUMNS_MEETUPS[10]="TO_TAG";
		COLUMNS_MEETUPS[11]="NAME";
		COLUMNS_MEETUPS[12]="GENDER";
		COLUMNS_MEETUPS[13]="STATUS";
		COLUMNS_MEETUPS[14]="CREATION_DATE";


		return COLUMNS_MEETUPS;

	}



	public static String TABLE_MEETUP_DETAILS="MEETUP_DETAILS";
	public static String[] COLUMNS_MEETUP_DETAILS;
	public static String[] getColumns_MEETUP_DETAILS(){
		COLUMNS_MEETUP_DETAILS=new String[8];
		COLUMNS_MEETUP_DETAILS[0]="MEETUPS_ID";
		COLUMNS_MEETUP_DETAILS[1]="USER_OID";
		COLUMNS_MEETUP_DETAILS[2]="USER_NAME";
		COLUMNS_MEETUP_DETAILS[3]="LAT";
		COLUMNS_MEETUP_DETAILS[4]="LONGI";
		COLUMNS_MEETUP_DETAILS[5]="PLACE_NAME";
		COLUMNS_MEETUP_DETAILS[6]="STATUS";
		COLUMNS_MEETUP_DETAILS[7]="CREATION_DATE";


		return COLUMNS_MEETUP_DETAILS;

	}


	@SuppressLint("SimpleDateFormat")
	public static String getDateTime()
	{

		final Calendar c = Calendar.getInstance();

		SimpleDateFormat df = new SimpleDateFormat("yyy-MM-dd HH:mm:ss");
		String formattedDate = df.format(c.getTime());
		return formattedDate;


	}
}

